name: portal_jtv
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # injection
  get_it: ^9.2.0

  # state management
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1

  # router
  go_router: ^17.0.1

  # network
  dio: ^5.9.1

  dartz: ^0.10.1
  equatable: ^2.0.8
  intl: ^0.20.2

  # mapping json to object
  json_annotation: ^4.10.0

  # create immutable class/object
  freezed_annotation: ^3.1.0

  shared_preferences: ^2.5.4
  share_plus: ^12.0.1

  flutter_html: ^3.0.0
  flutter_tts: ^4.2.5

  cached_network_image: ^3.4.1
  in_app_review: ^2.0.11

  # Media Kit packages for video playback
  media_kit: ^1.2.6 # Primary package.
  media_kit_video: ^2.0.1 # For video rendering.
  media_kit_libs_video: ^1.0.7 # Native video dependencies.
  webview_flutter: ^4.13.1
  media_kit_libs_android_video: ^1.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
    - assets/icons/navigation/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_24pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter_24pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter_24pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_24pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_24pt-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter_24pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_24pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter_24pt-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter_24pt-Italic.ttf
          style: italic
